# Generated by Django 4.2.5 on 2023-09-26 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
