# Generated by Django 4.2.5 on 2023-09-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
